# Query for TARA acupoint ontology anatomical entities with synonyms
# Only consider the acupoints studied in some article
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX partOf: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX ilxtr: <http://uri.interlex.org/tgbugs/uris/readable/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX TARA: <http://www.acupunctureresearch.org/tara/ontology/>


SELECT DISTINCT
# ?Acupoint_Label
?Anatomical_Region_IRI
?Anatomical_Region_Synonym
{
    ?Acupoint_IRI rdfs:subClassOf+/rdfs:label "Acupoint".
    # ?Acupoint_IRI rdfs:label ?Acupoint_Label.
    
    # Only include the acupoints that are studied in some article
    ?Acupoint_IRI TARA:isStudiedInArticle ?Studied_Article_IRI.
    ?Acupoint_IRI (TARA:hasSurfaceLocation | TARA:hasRelatedLocation) ?Anatomical_Region_IRI.
    
   OPTIONAL
   {
    ?Anatomical_Region_IRI (rdfs:label | NIFRID:synonym | oboInOwl:hasExactSynonym) ?Anatomical_Region_Synonym.
   }

  # Filter (?Acupoint_IRI != '').
}
ORDER BY ?Acupoint_Label
LIMIT 10000